### ISSUE TITLE
Windows Security identifies HijackThis as Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by beeka** [dragokas/hijackthis#101]
**Describe the bug**
On downloading the pre-built release binary or the test version, Windows Security reports the zip file as a threat (containing Trojan:Win32/Azden.A!cl) and quarantines it.

**To Reproduce**
1. Go to 'https://github.com/dragokas/hijackthis'
2. Click on 'Pre-built binary (release version) for Windows'
3. Select somewhere to save the zip file

**Expected behavior**
No threat detected.

**Screenshots**

![image](https://user-images.githubusercontent.com/13928331/89716161-9bcc2c80-d9a2-11ea-880b-6c8fddeab8d3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 Build 18363.959
 - HJT Version is not clear from the links.

**Additional context**
A google search for this trojan + hijackthis with does not show any useful hits.

**Comment by dragokas** [comment]
I know, thank you.
Please, report about false-positive directly to Microsoft using this link: https://www.microsoft.com/en-us/wdsi/filesubmission/
marking it as "Incorrectly detected as malware/malicious".

For further reference, you can use links from this topic to report to any AV vendor:
https://safezone.cc/threads/kuda-soobschit-o-lozhnom-srabatyvanii-antivirusa.23501/

Also, don't mark topic as "bug", because it is a bug not in my software, but in the Microsoft software.

**Comment by dragokas** [comment]
Microsoft is fixed it:
https://www.virustotal.com/gui/file/267ea49c9eced989ad8a0481ff6d60d71fa93b18312e79f1707889ec88850739/detection
