### ISSUE TITLE
Exe files (Neshta)

### ISSUE THREAD

**Issue by jimmy5330-dot** [dragokas/hijackthis#220]
Welcome!
Thank you for joining the section of VIRUSNET association support.
_________________________________________________________________
### BEFORE ASKING HELP, READ CAREFULLY THIS INSTRUCTION:
_________________________________________________________________

### Step 1: Show us the required logs (for PC cure only):

  * Read carefully: "How to make a request for help in the PC cure section":
https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F

  * Attach 'Collection-[Date].zip' log created by "AutoLogger" tool:
https://www.safezone.cc/resources/autologger-regist-drongo.59/download

### Step 2: Describe your problem in details:

1. What did you done before the problem occurs: _Fix exe assocation________________
2. What programs (browsers) affected by the problem: __All______________
3. Steps to reproduce: ___Reboot______________
4. Expected behavior: _Exe file not working________________
5. If applicable, add screenshots to help explain your problem.
[CollectionLog-2023.08.27-08.58.zip](https://github.com/dragokas/hijackthis/files/12448071/CollectionLog-2023.08.27-08.58.zip)

**Comment by dragokas** [comment]
Hi, 
thank you for the log.

You have a file virus "Neshta", which damage all exe files in real-time. Simple exe association fix will not help. None of AV tools ran directly from infected OS can't help as well.
The only possible solution to cure this kind of infection is:
 - Prepare LiveCD (or flash-drive), using instruction:
 * https://www.kaspersky.com/downloads/free-rescue-disk
 or
 * https://free.drweb.com/aid_admin/?lng=en
- It's better to prepare CD on other virus-free PC
- Then, shut down your PC
- insert LiveCD (flash-drive)
- set up your PC to boot from CD/flash
- follow the instructions when boot from LiveCD
- you must do a full scan with automatic cure of all your drives
- be attentive: if you ever inserted your external drives/other flash-drives or accessed to network shares, all of them are infected too!
- you need to make full scan of such drives too, e.g. with Dr.Wev CureIt utility

My personal favor: to use drweb utility and its LiveCD, because it is able at least try to restore your damaged exe files instead of complete removing them unlike other vendors.

Alternatively - if instead of cure, you're planning to reinstall your OS completely:
 - do not try to install system on the same drive without full format. 
 - do not prepare CD/flash on infected PC
 - do a full scan of ALL your drives, external drives and flash drives with antivirus as soon as you'll finish install the system
 - do not run or install anything from anywhere before you'll finish full antivirus scan and cure

----------------------------------------------------------------------------------------------------
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. 
Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by dragokas** [comment]
Closed.
Reason: no answer for 10 days.
If you still need our help, please, execute the last steps, requested by a helper.
Also, download again [AutoLogger](https://tools.safezone.cc/drongo/AutoLogger/AutoLogger.zip), prepare new CollectionLog, and write what problems remained.
