### ISSUE TITLE
Need help looking over Hijackthis.log

### ISSUE THREAD

**Issue by FMB2K9** [dragokas/hijackthis#242]
< log has been deleted > by Moderator.

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

Please **attach** requested logs instead of pasting it into message.

**Comment by FMB2K9** [comment]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/14200228/HiJackThis.log)
