### ISSUE TITLE
HijackThis Heuristic Ransomware Encrypted File Detection Without Rely On Antivirus

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [dragokas/hijackthis#259]
**Is your feature request related to a problem? Please describe.**

No. It's new thing.

**Describe the solution you'd like**

https://github.com/HydraDragonAntivirus/HydraDragonAVHaiku/blob/main/HydraDragonAntivirus/knownExtensions.cpp
We just need use this list then look there two extensions exist or not and then look is last extension unknown then look previous extension if previous extension known and it contains hex with unreadable non ascii text then it's possible Ransomware
**Describe alternatives you've considered**
An Alternative Solution is after detecting possible ransomware file use machine learning to detect is file really encrypted

**Additional context**
I will help this project must as be possible to HijackThis reach old good days.

**Comment by dragokas** [comment]
Hi,
instead of textual description, please provide in-the-wild indicator of compromise or the name of ransomware you're referring to.
I didn't get what is provided extensions list intended for.
Even, if HJT will detect the sign of renamed extensions or ensures that it is really the encrypted file, it does not mean the system contain the ransomware anymore. E.g. it might be already cured or self-destroyed.
HJT detects malware in autorun locations where malware ensures its persistence. Other derivatives has no much sense for curing the infection, because it is not "after-encryption file restore tool" and cannot be.

**Comment by HydraDragonAntivirus** [comment]
> Hi, instead of textual description, please provide in-the-wild indicator of compromise or the name of ransomware you're referring to. I didn't get what is provided extensions list intended for. Even, if HJT will detect the sign of renamed extensions or ensures that it is really the encrypted file, it does not mean the system contain the ransomware anymore. E.g. it might be already cured or self-destroyed. HJT detects malware in autorun locations where malware ensures its persistence. Other derivatives has no much sense for curing the infection, because it is not "after-encryption file restore tool" and cannot be.

Oh okay. It seems like we can detect this before encryption but then this different project due to this: If you read hex of Ransomware and if their unknown extension here with my requirements it really detect ransomware with low false positives. I think I should create another project because it seems like most people didn't know how to use vb6.

**Comment by dragokas** [comment]
I repeat you one more time HJT is not antivirus. It's post-infection tool. See the description.
vb6 is dead for ages. There is community newcomer with release date of end 2024: twinBASIC.
vba is also becoming dead. There is python now in office.
vbscript is also deprecated by Microsoft this year. So all official Basics are almost dead.
This project is the heir of the original, that's why he saved the language, which was lovely by lot of people. The only thing which was sorely lacking - this is an analogue of NuGet. Now, twinBasic author already implemented something similar.
At the moment, the development of HJT fork is completely dead, because of the war in Ukraine. The parliament is waging war on its own people by making the genocide of the male population by forcibly sending everyone to the frontline, making a lot of money by kidnapping people on the streets.

**Comment by Siradankullanici** [comment]
I'm HydraDragonAntivirus. I make my account organization sorry for that. I was going to use detectiteasy to detect any possible ransomware infection and improving HijackThis for that if you want. Edit: HijackThis probably not good tool for that.
