### ISSUE TITLE
check for updates is broken !

### ISSUE THREAD

**Issue by mloh908** [dragokas/hijackthis#28]
Hijackthis - check for updates option is no longer works ! can you fix this ?

**Comment by dragokas** [comment]
Hi,
thank you for reporting.
I know about this issue.
Unfortunately, it can't be fixed on server side, because GitHub set a redirection that HJT is not yet supported.
So, update option will work correctly in new version of HJT only in the nearest update.

Have a nice day,
Stanislav.

**Comment by dragokas** [comment]
Problem is fixed in [test-build](https://dragokas.com/tools/HiJackThis_test.zip) and will go to the nearest release.
Please, note: that test-version can only check for new release version update (not new test-version).
Also, GitHub is currently dropped from the list of sites where HJT query for update due to problems with https in IE8. Now, link is replaced by dragokas.com
