### ISSUE TITLE
Hebrew fonts

### ISSUE THREAD

**Issue by limelect** [dragokas/hijackthis#36]
I just used HijackThis Fork Portable 3 and saw after scanning that Hebrew names are jibrish.
In the log it is OK .
May be using Aerial font will do? 
Or add on setup Font manger

**Comment by dragokas** [comment]
Hi, @limelect !

Thank you for feedback!

I'm not familiar with East-Asian font family. So, I need your help in order to fix fonts according to your PC locale settings.
1) Please, provide such line from the log:

> Language:  OS: Russian (0x419). Display: Russian (0x419). Non-Unicode: Russian (0x419)

2) Please, attach a screenshot of program window where you think incorrect characters appear. Also, highlight for me, please, what characters are wrong.

3) Provide me a txt file with the same (correct) characters (as they should be) and save file using UTF-16 LE format.

Currently, fonts are automatically adjusted depending on User Locale ID. I took if from Bellecom's code (looks like 'Gun' and 'Adult' members helped him). The same I found in MSDN: https://msdn.microsoft.com/en-us/library/aa241713(v=vs.60).aspx
I don't quite agree with it. Maybe I should use 'Current display language' as a mark.
So, current rules are:
 - For LCID 0x404 (Chinese (Traditional) - Taiwan)
Font.Charset = CHINESEBIG5_CHARSET
Font.Name = 新細明體 (New Ming-Li)
 - For LCID 0x411 (Japanese - Japan)
Font.Charset = SHIFTJIS_CHARSET
Font.Name = ＭＳ Ｐゴシック
 - For LCID 0x412 (Korean - Korea)
Font.Charset = HANGEUL_CHARSET
Font.Name = 굴림
 - For LCID 0x804 (Chinese (Simplified) - People's Republic of China)
Font.Charset = CHINESESIMPLIFIED_CHARSET
Font.Name = 宋体

And for all cases Font.Size = 9 (a little bit larger than default one).

If you have some recommendations feel free to suggest better solution.

Best regards,
Stanislav.

**Comment by limelect** [comment]
No need for Locale ID just give me to choose a font and put in INI
This will solve the problem with fonts on your list.
 Locale ID can be for the first time but then will change.
IN the text editor the text is OK.
so the problem is only on the list.

In Delphi that i work with there is a font chooser i suspect you 
have the same with Basics.
Usually i choose "arial" it give a global solution.
 If you want send me a test program so i can give you a feedback.
P.S My site www.limelect.com  lots of free programs can help in developments.

**Comment by dragokas** [comment]
That's interesting suggestion.
I'll add such option and let you know.

**Comment by dragokas** [comment]
Anyway can you please provide the requested info, please?
So, I can improve automatic font choice behaviour.

**Comment by limelect** [comment]
"Anyway can you please provide the requested info, please?
So, I can improve automatic font choice behaviour."
How do i do it?????
I do not understand what you want?

**Comment by dragokas** [comment]
- Run the program. Press button "Do a system scan and save a log file".
Show me only the 5-th line, like this:
> Language:  OS: xxx (0xxx). Display: xxx (0xxx). Non-Unicode: xxx (0xxx)
 - attach a screenshot of program window where you think incorrect characters appear. Also, highlight for me, please, what characters are wrong.
 - create and attach a text file (in UTF-16 LE format) with the same (correct) characters (as they should be). 
(You can use Notepad => save as... Codepage => Unicode.)

**Comment by limelect** [comment]
Logfile of HiJackThis Fork (Beta) by Alex Dragokas v.2.8.0.4

Platform:  x64 Windows 7 (Pro), 6.1.7601.24180, Service Pack: 1
Time:      10.08.2018 - 09:52 (UTC+03:00)
Language:  OS: English (0x409). Display: English (0x409). Non-Unicode: Hebrew (0x40D)
Elevated:  Yes
Ran by:    LimElect	(group: Administrator) on LIMELECT-THINK, FirstRun: yes

**Comment by limelect** [comment]
[HiJackThis.log](https://github.com/dragokas/hijackthis/files/2280503/HiJackThis.log)

line 339 in hebrew on my computer OK

**Comment by limelect** [comment]
You are pursuing the wrong solution
Just give the user the possibility to choose a font
and put in INI

**Comment by dragokas** [comment]
@limelect, 
> I'll add such option and let you know.

I will send you link as soon as it will be ready.

BTW, thank you for the log.

![settings](https://user-images.githubusercontent.com/19956568/43995688-73a6a818-9dbb-11e8-85c7-4d2f05720bbe.png)

**Comment by dragokas** [comment]
Hi, @limelect !

Try this version: https://dragokas.com/tools/HiJackThis_test.zip

File => Settings => Interface:
 - Font
 - Size
 - (optional) Apply selected font on lists of scan results and input windows only

Please, infrorm me if 'Arial Unicode MS' font is good enough suitable for Hewbrew.

**Comment by limelect** [comment]
Ok it works It took me a wile
I try arial and arial (hebrew) - nothing
I tried microsoft sans serif - nothing
i tried microsoft serif  - OK !!!
i tried meriam << hebrew fonts - OK
So you have it.
One more thing i do not think that the PAGE font have to change ONLY THE LIST BOX.
But it is up to you.
If you need my help do not hesitate
Do not forget to up date the portable too.
Great job

**Comment by limelect** [comment]
Ok i just saw this (optional) Apply selected font on lists of scan results and input windows only
So every thing OK great

**Comment by dragokas** [comment]
There are:
 - Arial
 - Arial Unicode MS
Did you try both?

Thank you for test and report.

**Comment by dragokas** [comment]
Do you mean "Miriam"? I think font size = 10 is looking nice, isn't it?
Is "Microsoft Serif" also OK for hebrew?

**Comment by dragokas** [comment]
I uploaded new version where I set font's character set to HEBREW_CHARSET.
Can you please re-download program and check again each font of 'Arial' family?

**Comment by limelect** [comment]
Arial Unicode MS - NO
i tried microsoft serif - OK !!!
i tried meriam << hebrew fonts - OK

**Comment by limelect** [comment]
I did not download as i do not know where from. All links are old.
Send a test program. i used the last one you send

**Comment by limelect** [comment]
OK i downloaded new .It is OK

**Comment by dragokas** [comment]
Results are the same? Or something changed?

**Comment by dragokas** [comment]
Also, in the last version I set HiJackThis automatically choose "Miriam" font for Hebrew (listboxes and input windows only). If you want you can check it => press File => Uninstall HJT. It will remove all settings.

**Comment by limelect** [comment]
I personally  start with  "MS serif" it is common in all computers  otherwise every thing OK

**Comment by dragokas** [comment]
OK, thank you for all the tests.
Update will be included in the next public release.
