### ISSUE TITLE
PC running slow, bluescreens without a topic and issues..

### ISSUE THREAD

**Issue by xJaydox** [dragokas/hijackthis#57]
Hey, I only managed it to save the log.txt file.
Hopefully you can see what's wrong with this one.

Checked the RAM, checked all HDD's and SSD's .. nothing changed. Even just with 8GB Ram (new) and the System SSD (1TB, new) everything's the same.

I could imagine it's the mainboard running down on it. 

[HiJackThis.log](https://github.com/dragokas/hijackthis/files/2685961/HiJackThis.log)

**Comment by Sandor-Helper** [comment]
Hello and welcome!

Please do additional some logs using [this guide](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F).

**Comment by xJaydox** [comment]
[CollectionLog-2018.12.17-14.55.zip](https://github.com/dragokas/hijackthis/files/2686315/CollectionLog-2018.12.17-14.55.zip)

After the 3rd time I managed it. Got a bluescreen after that.

**Comment by Sandor-Helper** [comment]
I didn't find any malicious record in logs. 

Since your problem is not malware-related, we recommend you to ask help on the forums that provide assistance in resolving general operation system issues, like:

- https://www.sevenforums.com/
- https://answers.microsoft.com/
- http://www.geekstogo.com/forum/forum/41-operating-systems/

**Comment by xJaydox** [comment]
Thank you.
