### ISSUE TITLE
Can you add tags/releases/binaries?

### ISSUE THREAD

**Issue by Neustradamus** [dragokas/hijackthis#94]
Can you add tag/release and compiled builds too like all other softwares?
- https://github.com/dragokas/hijackthis/releases
- https://github.com/dragokas/hijackthis/tags

**Comment by dragokas** [comment]
There are no new binaries on "release" page at the moment.
All binaries are available on the project's main page or in the "binary" subfolder: https://github.com/dragokas/hijackthis/tree/devel/binary

The most recent version (nightly build) is available by the link:
https://dragokas.com/tools/HiJackThis_test.zip

I will think about adding binary in the "release page" with the upcoming update since it is a long time ago not an Alpha, nor Beta anymore.
Thanks for reminder.

**Comment by dragokas** [comment]
I'll leave it open so not to forget with updating "release" page.

**Comment by dragokas** [comment]
Without following the "release" / main page, you can also have an option to check updates manually / automatically using own HiJackThis Fork interface:
 - just click Help -> Check for updates
 - or select appropriate options in menu "Misc Tools" -> "Updates" section.

**Comment by Neustradamus** [comment]
Warning: Binaries must not be included in the code directly!

It is for this that there are "releases" section to have all packages:
- sourcecode
- binairies

**Comment by dragokas** [comment]
Yes, we decided not follow this best practice until v3.0 will finally out,
to have a chance to test our software as much thoroughly as possible before official release,
since any antivirus software is always a high risk software.

**Comment by dragokas** [comment]
Released as v2.9.0.26

**Comment by Neustradamus** [comment]
@dragokas: Excellent, thanks a lot!

Please do tags and releases for each releases (not only the 2.9.0.26)

**Comment by dragokas** [comment]
There is no need. HiJackThis has a lot of update options under "Updates" section of "Misc Tools" menu, including notification only or self auto-update.
I will do only essential updates under "release" tab.
